// List your page image filenames below, in reading order.
// Example: "pages": ["page-01.png", "page-02.png", "page-03.png"]
window.CLUTCH_MANIFEST = {
  "issue": 9,
  "pages": [
    "Cover.webp",
    "p1.webp",
    "p2.webp",
    "p3.webp",
    "p4.webp",
    "p5.webp",
    "p6.webp",
    "p7.webp",
    "p8.webp",
    "p9.webp",
    "p10.webp",
    "p11.webp",
    "p12.webp",
    "p13.webp",
    "p14.webp",
    "p15.webp",
    "p16.webp",
    "p17.webp",
    "p18.webp",
    "p19.webp",
    "p20.webp",
    "p21.webp",
    "p22.webp",
    "p23.webp",
    "p24.webp",
    "p25.webp",
    "p26.webp",
    "p27.webp",
    "p28.webp",
    "p29.webp",
    "p30.webp",
    "p31.webp",
    "p32.webp",
    "p33.webp",
    "p34.webp",
    "p35.webp",
    "p36.png"
  ]
};
