// ==========================================================================
//  AD&D 2e — one-line spell EFFECT descriptors (window.SPELL_EFFECT)
//  Short "what it does" tag shown on each Spellbook row (distinct font),
//  falling back to the spell's dmg dice when absent. Keyed by display name
//  (resolved case-insensitively). Grow this toward all ~365 PHB spells.
// ==========================================================================
(function(){
  window.SPELL_EFFECT = {
    // — Wizard —
    'Magic Missile':'1d4+1 × auto-hit darts',
    'Burning Hands':'1d3/lvl fire cone',
    'Charm Person':'charm 1 humanoid',
    'Sleep':'2d4 HD fall asleep',
    'Shield':'+AC, stops missiles',
    'Feather Fall':'drift down safely',
    'Light':'light a 20-ft radius',
    'Detect Magic':'sense magic auras',
    'Identify':'learn an item\u2019s powers',
    'Grease':'slick 10-ft square',
    'Color Spray':'1d6 foes dazed/blind',
    'Enlarge':'grow or shrink target',
    'Mount':'summon a steed',
    'Spider Climb':'walk walls & ceilings',
    'Web':'entangle a 20-ft cube',
    'Invisibility':'become unseen',
    'Mirror Image':'1d4 duplicate decoys',
    'Knock':'open locks & bars',
    'Levitate':'rise & sink at will',
    'Stinking Cloud':'nauseating gas cloud',
    'Melf\u2019s Acid Arrow':'2d4 acid, lingers',
    'Fireball':'1d6/lvl fire, 20-ft ball',
    'Lightning Bolt':'1d6/lvl arcing line',
    'Fly':'true flight',
    'Haste':'double move & +1 attack',
    'Slow':'halve foes\u2019 speed & attacks',
    'Dispel Magic':'cancel active magic',
    'Hold Person':'paralyze 1\u20134 people',
    'Suggestion':'compel a reasonable act',
    'Fear':'flee in a cone',
    'Vampiric Touch':'drain HP to yourself',
    'Ice Storm':'3d10 cold / hail barrage',
    'Wall of Fire':'2d6 blazing wall',
    'Charm Monster':'charm any creature(s)',
    'Confusion':'foes act at random',
    'Dimension Door':'blink up to 30 yds',
    'Polymorph Self':'take another form',
    'Polymorph Other':'transform a target',
    'Fire Shield':'ward + retaliate w/ fire',
    'Stoneskin':'ignore N physical hits',
    'Cone of Cold':'1d4+1/lvl freezing cone',
    'Hold Monster':'paralyze any 1\u20134',
    'Cloudkill':'rolling lethal fog',
    'Feeblemind':'wreck a caster\u2019s mind',
    'Wall of Force':'impassable clear wall',
    'Teleport':'instant long-range jump',
    'Disintegrate':'erase target or matter',
    'Death Spell':'slay low-HD masses',
    'Chain Lightning':'bolt leaps foe to foe',
    'Flesh to Stone':'petrify a creature',
    'Wall of Ice':'frozen barrier',
    'Delayed Blast Fireball':'timed 1d6+/lvl blast',
    'Finger of Death':'slay one (save or die)',
    'Power Word, Stun':'stun a wounded foe',
    'Prismatic Spray':'seven random ray effects',
    'Mass Invisibility':'hide a whole group',
    'Meteor Swarm':'4 fireballs at once',
    'Power Word, Kill':'kill outright, no save',
    'Time Stop':'1d3 free rounds',
    'Wish':'reshape reality',
    'Prismatic Sphere':'7-layer killing ward',
    // — Priest —
    'Cure Light Wounds':'heal 1d8',
    'Bless':'allies +1 hit & morale',
    'Curse':'foes \u22121 hit & morale',
    'Command':'one-word compulsion',
    'Sanctuary':'foes must save to attack',
    'Detect Evil':'sense evil intent',
    'Protection From Evil':'\u22122 to evil, blocks entry',
    'Aid':'1d8 temp HP + to-hit',
    'Barkskin':'+AC, tough as bark',
    'Find Traps':'reveal nearby traps',
    'Hold Person ':'paralyze 1\u20133 people',
    'Silence, 15\u2019 Radius':'zone of total silence',
    'Slow Poison':'delay venom\u2019s onset',
    'Spiritual Hammer':'floating force weapon',
    'Augury':'omen: weal or woe',
    'Continual Light':'permanent bright light',
    'Dispel Magic ':'cancel active magic',
    'Cure Blindness or Deafness':'restore sight/hearing',
    'Prayer':'allies +1 / foes \u22121',
    'Remove Curse':'lift a curse',
    'Animate Dead':'raise skeletons/zombies',
    'Cure Serious Wounds':'heal 2d8+1',
    'Neutralize Poison':'purge venom',
    'Protection From Evil, 10\u2019 Radius':'group anti-evil ward',
    'Flame Strike':'6d8 fiery pillar',
    'Raise Dead':'return the dead to life',
    'True Seeing':'see all as it truly is',
    'Commune':'yes/no from your god',
    'Heal':'restore all but 1d4 HP',
    'Harm':'reduce foe to 1d4 HP',
    'Word of Recall':'teleport to sanctuary',
    'Regenerate':'regrow lost limbs',
    'Resurrection':'fully revive the dead',
    'Earthquake':'shatter the ground',
    'Gate':'summon a deific being',
    'Cure Critical Wounds':'heal 3d8+3',
    'Restoration':'restore a drained level',
    'Sticks to Snakes':'sticks become serpents',
    'Insect Plague':'swarm drives off foes',
    'Holy Word':'smite & banish evil',
    // — Wizard (batch 2, richer) —
    'Read Magic':'decipher arcane script, 2 rd/lvl',
    'Comprehend Languages':'read any writing, 5 rd/lvl',
    'Jump':'leap 30 ft forward, 1+/lvl jumps',
    'Spook':'target flees in fear (save at \u22121/lvl)',
    'Blur':'\u22124 foes\u2019 first hit, then \u22122; +1 saves',
    'Detect Invisibility':'see invisible/hidden, 5 rd/lvl',
    'ESP':'read surface thoughts, 90 ft, 1 rd/lvl',
    'Flaming Sphere':'2d4 fire, rolls 30 ft/rd, 1 rd/lvl',
    'Ray of Enfeeblement':'\u221225% Strength, 1 rd/lvl',
    'Rope Trick':'6 hide in pocket space, 2 turns/lvl',
    'Scare':'sub-6-HD freeze in terror 1d4 rd',
    'Blink':'vanish/reappear 2 ft, ~75% melee miss',
    'Hold Undead':'freeze 1d3 undead, 1 rd/lvl',
    'Monster Summoning I':'2\u20134 minor monsters, 2 rd/lvl',
    'Protection From Normal Missiles':'immune to non-magic shots, 1 turn/lvl',
    'Water Breathing':'breathe water, 1 hour/lvl',
    'Tongues':'speak & grasp any tongue, 1 rd/lvl',
    'Enervation':'drain 1d4 levels, 1 hour/lvl',
    'Minor Globe of Invulnerability':'blocks lvl 1\u20133 spells, 5 ft',
    'Phantasmal Killer':'illusory horror, save vs death or die',
    'Wizard Eye':'fly a scout eye 30 ft/rd, 1 rd/lvl',
    'Telekinesis':'move 25 lb/lvl by mind, 1 rd/lvl',
    'Passwall':'open a 5\u00d78\u00d710 ft tunnel in stone',
    'Conjure Elemental':'summon a 16-HD elemental',
    'Domination':'lasting charm-command, telepathic',
    'Magic Jar':'possess bodies from a soul-jar',
    'Globe of Invulnerability':'blocks lvl 1\u20134 spells, 5 ft',
    'Bigby\u2019s Forceful Hand':'wall-hand shoves foes back',
    'Reverse Gravity':'everything falls up 1 rd',
    'Mordenkainen\u2019s Sword':'force blade, 5d4/5d6, 1 rd/lvl',
    'Mass Charm':'charm up to 2 HD/lvl of foes',
    'Maze':'banish to a demiplane 1+ rd',
    'Limited Wish':'reshape reality (limited)',
    // — Priest (batch 2, richer) —
    'Create Water':'conjure 4 gallons/lvl',
    'Endure Cold / Endure Heat':'ignore harsh temps, 9 turns/lvl',
    'Remove Fear':'+4 save vs fear; cancel existing',
    'Resist Fire / Resist Cold':'+3 saves, \u22121/die vs that energy',
    'Chant':'allies +1 hit/dmg/save, foes \u22121',
    'Enthrall':'captivate a crowd while you speak',
    'Speak With Animals':'converse with beasts, 2 rd/lvl',
    'Create Food & Water':'feed 3 people+/lvl for a day',
    'Cure Disease':'cure illness, rot & infestation',
    'Speak With Dead':'ask a corpse a few questions',
    'Free Action':'move unhindered by web/hold/water',
    'Dispel Evil':'banish fiends; +7 save vs them',
    'Cause Critical Wounds':'inflict 3d8+3 on touch',
    'Blade Barrier':'8d8/rd spinning blade wall',
    'Heroes\u2019 Feast':'meal: full heal + fear/poison immunity',
    'Wind Walk':'become mist, travel 600 ft/rd',
    'Control Weather':'shift the weather one step',
    'Wall of Thorns':'thorny barrier, 8+ dmg to cross',
    'Conjure Animals':'summon beasts, 2 HD/lvl total',
    'Symbol':'glyph triggers death/fear/stun/etc.',
    // — Wizard (batch 3) —
    'Armor':'grants AC 6 until 8+ dmg taken',
    'Chill Touch':'1d4 + 1 Str drain, ghostly hand',
    'Find Familiar':'summon a bonded familiar',
    'Unseen Servant':'invisible force does light tasks',
    'Tenser\u2019s Floating Disc':'hovering disc hauls 100 lb',
    'Hypnotism':'lull 1d6 into suggestibility',
    'Shocking Grasp':'1d8+1/lvl electric touch',
    'Wall of Fog':'obscuring fog, 2d4+ rd',
    'Change Self':'alter your appearance, 2d6+ rd',
    'Alarm':'audible ward on a 20-ft area',
    'Dancing Lights':'up to 4 drifting lights',
    'Continual Light':'permanent daylight globe',
    'Fog Cloud':'drifting fog, obscures 40 ft',
    'Glitterdust':'blind foes & reveal invisible',
    'Strength':'+1d4\u20131d8 Strength, 1 hr/lvl',
    'Summon Swarm':'biting swarm, 2 rd/lvl',
    'Clairvoyance':'see a distant known place',
    'Clairaudience':'hear a distant known place',
    'Flame Arrow':'1d6 fire per 2 lvls, or +1d6 ammo',
    'Wind Wall':'gale wall stops arrows & gas',
    'Leomund\u2019s Tiny Hut':'cozy 5-ft dome, 1 hr/lvl',
    'Phantom Steed':'quasi-real mount, fast',
    'Improved Invisibility':'unseen even while attacking',
    'Evard\u2019s Black Tentacles':'tentacles grapple & crush',
    'Solid Fog':'fog that halts movement',
    'Wall of Iron':'conjure a sheet of iron',
    'Wall of Stone':'conjure a stone barrier',
    'Stone Shape':'mold 1 cu ft+/lvl of stone',
    'Animal Growth':'double up to 8 creatures\u2019 size',
    'Sending':'25-word message, any distance',
    'Antimagic Shell':'10-ft zone blocks all magic',
    'Geas':'compel a task; sicken if refused',
    'Legend Lore':'learn a person/place/thing\u2019s lore',
    'True Seeing':'pierce illusion, see true forms',
    'Banishment':'hurl outsiders from the plane',
    'Spell Turning':'reflect spells back at caster',
    'Mind Blank':'immune to mind & divination magic',
    'Energy Drain':'strip 2 levels like a wraith',
    'Shape Change':'become any creature at will',
    'Imprisonment':'entomb a victim indefinitely',
    // — Priest (batch 3) —
    'Entangle':'plants grip a 40-ft area',
    'Faerie Fire':'outline foes, +to-hit vs them',
    'Goodberry':'2d4 berries heal 1 & sustain',
    'Shillelagh':'cudgel strikes +1 for 2d4',
    'Flame Blade':'fiery blade, 1d4+4 (more vs undead)',
    'Heat Metal':'metal sears or freezes, 1d4+/rd',
    'Produce Flame':'hurl flame for 1d4+1',
    'Call Lightning':'3d6 + 1d6/lvl bolt from a storm',
    'Glyph of Warding':'rune detonates on trespass',
    'Magical Vestment':'vestments become +3 armor',
    'Water Walk':'stride across water, 1 turn/lvl',
    'Detect Lie':'sense truth from falsehood',
    'Air Walk':'walk on air as on ground',
    'Plane Shift':'step to another plane',
    'Fire Seeds':'acorns/berries become fire bombs',
    'Find the Path':'unerring route to a place',
    'Fire Storm':'roaring flame sheet, 2d4/lvl',
    'Sunray':'blinding burst; sears undead',
    'Creeping Doom':'crawling carpet of biting bugs',
    'Call Woodland Beings':'summon forest allies',
    // — Wizard (batch 4) —
    'Nystul\u2019s Magic Aura':'fake (or mask) an item\u2019s aura',
    'Taunt':'goad foes into charging you',
    'Wizard Mark':'inscribe a hidden personal sigil',
    'Deafness':'strike a target deaf (save neg.)',
    'Magic Mouth':'set a triggered spoken message',
    'Misdirection':'throw off divination magic',
    'Explosive Runes':'6d4+ blast when read (save half)',
    'Item':'shrink objects to cloth for hauling',
    'Non-Detection':'hide from scrying, 1 hr/lvl',
    'Spectral Force':'illusion with sound, smell & feel',
    'Dig':'excavate a 5-ft cube per round',
    'Emotion':'sway a group: fear, rage, hope, calm',
    'Enchanted Weapon':'make a temporary magic weapon',
    'Hallucinatory Terrain':'disguise the landscape',
    'Massmorph':'hide up to 100 troops as trees',
    'Minor Creation':'conjure plant-based matter',
    'Plant Growth':'thicken brush into dense thicket',
    'Rainbow Pattern':'lights fascinate & lead away',
    'Shout':'thunder cone, 2d6 + deafen',
    'Chaos':'confusion across a group of foes',
    'Dream':'send a message through dreams',
    'Fabricate':'shape raw stock into finished goods',
    'Major Creation':'conjure matter, even metal',
    'Seeming':'redisguise a whole group\u2019s look',
    'Contingency':'store a spell to auto-cast on a trigger',
    'Eyebite':'gaze: charm, fear, sicken, or sleep',
    'Move Earth':'reshape hills & terrain over time',
    'Otiluke\u2019s Freezing Sphere':'cold burst, ray, or globe',
    'Reincarnation':'the dead return in a new body',
    'Stone to Flesh':'restore petrified (or flesh a foe)',
    'Tenser\u2019s Transformation':'become a whirlwind fighter',
    'Forcecage':'inescapable cage of force',
    'Phase Door':'step through a wall, 1/turn',
    'Simulacrum':'craft a half-strength duplicate',
    'Teleport Without Error':'flawless teleport, any distance',
    'Otto\u2019s Irresistible Dance':'victim dances helplessly',
    'Permanency':'make a chosen spell permanent',
    'Polymorph Any Object':'transform anything into anything',
    'Power Word, Blind':'blind foes (by their hit points)',
    'Prismatic Wall':'seven-layer wall of deadly light',
    'Foresight':'sense danger minutes ahead',
    'Mordenkainen\u2019s Disjunction':'strip all magic in a 30-ft radius',
    'Weird':'illusory nemesis, save vs death or die',
    // — Priest (batch 4) —
    'Pass Without Trace':'leave no track or scent',
    'Charm Person or Mammal':'befriend a person or beast',
    'Dust Devil':'minor whirlwind, 1d4/rd',
    'Obscurement':'misty cloud veils a 10-ft/lvl area',
    'Wyvern Watch':'guardian stuns the first intruder',
    'Hold Animal':'paralyze 1d4 animals',
    'Meld into Stone':'merge your body into rock',
    'Pyrotechnics':'fireworks blind, or smoke chokes',
    'Spike Growth':'ground spikes wound & slow crossers',
    'Summon Insects':'biting insect swarm attacks',
    'Cause Serious Wounds':'inflict 2d8+1 on touch',
    'Spell Immunity':'grant immunity to one spell',
    'Commune with Nature':'sense the land for miles',
    'Moonbeam':'pale beam reveals & marks foes',
    'Spike Stones':'stone spikes wound & trap',
    'Animate Object':'bring objects to fighting life',
    'Speak with Monsters':'converse with any creature',
    'Transport via Plants':'step from plant to distant plant',
    'Conjure Earth Elemental':'summon a 16-HD earth elemental',
    'Reincarnate':'a soul returns in a random new body',
    // — Wizard (batch 5) —
    'Affect Normal Fires':'shrink or flare flames',
    'Erase':'wipe 1\u20132 pages of writing',
    'Friends':'boost reaction, +Cha briefly',
    'Gaze Reflection':'bounce gaze attacks back',
    'Hold Portal':'hold a door shut, 1 rd/lvl',
    'Detect Undead':'sense undead within 60 ft',
    'Fool\u2019s Gold':'copper looks like gold coin',
    'Hypnotic Pattern':'shifting lights entrance foes',
    'Irritation':'itch & rash hamper a target',
    'Whispering Wind':'send a breeze-borne message',
    'Alter Self':'reshape your own body briefly',
    'Illusionary Script':'text baffles unintended readers',
    'Sepia Snake Sigil':'rune freezes the reader in stasis',
    'Delude':'mask your aura & alignment',
    'Illusionary Wall':'fake wall, floor, or ceiling',
    'Fire Trap':'warded object bursts 1d4+/lvl fire',
    'Advanced Illusion':'self-running moving illusion',
    'False Vision':'feed scryers a staged scene',
    'Mordenkainen\u2019s Faithful Hound':'invisible guard dog, 3d6 bite',
    'Summon Shadow':'raise shadow servitors',
    'Death Fog':'killing acidic fog bank',
    'Ensnarement':'lure & trap a summoned fiend',
    'Invisible Stalker':'summon an unseen hunter',
    'Mirage Arcana':'grand illusory terrain & buildings',
    'Mislead':'unseen while a double acts',
    'Part Water':'split a body of water',
    'Programmed Illusion':'illusion fires on a set cue',
    'Veil':'cloak an area in convincing illusion',
    'Control Undead':'command undead, 1 rd/lvl',
    'Drawmij\u2019s Instant Summons':'teleport a marked item to hand',
    'Mordenkainen\u2019s Magnificent Mansion':'enter a lavish demiplane',
    'Shadow Walk':'travel fast via the Shadow plane',
    'Vision':'seek an answer from higher powers',
    'Incendiary Cloud':'blazing cloud, rising fire dmg',
    'Screen':'hide an area from sight & scrying',
    'Trap the Soul':'imprison a soul within a gem',
    'Temporal Stasis':'freeze a victim in time',
    'Succor':'token whisks a set ally to you',
    // — Priest (batch 5) —
    'Invisibility to Animals':'beasts cannot sense you',
    'Locate Animals or Plants':'find a species nearby',
    'Purify Food & Drink':'cleanse tainted provisions',
    'Messenger':'a small animal carries your note',
    'Snake Charm':'entrance nearby snakes',
    'Warp Wood':'bend & ruin wooden gear',
    'Negative Plane Protection':'ward vs one drain touch',
    'Protection from Fire':'absorb a pool of fire damage',
    'Tree':'take the shape of a tree',
    'Imbue with Spell Ability':'lend a spell to a non-caster',
    'Speak with Plants':'converse with vegetation',
    'Atonement':'cleanse a broken vow or alignment',
    'Quest':'lay a compulsion toward a task',
    'Forbiddance':'seal an area by alignment/plane',
    'Changestaff':'staff becomes a treant ally',
    'Exaction':'demand service from an outsider',
    'Weather Summoning':'call a large weather front',
    'Wall of Fire ':'blazing wall, 2d4+1/lvl',
    // — final batch (remaining PHB spells) —
    'Cantrip':'minor apprentice tricks',
    'Precipitation':'a brief, light rain',
    'Deeppockets':'a garment holds far more gear',
    'Leomund\u2019s Trap':'feign a magical trap',
    'Detect Scrying':'know when you\u2019re being watched',
    'Extension I':'lengthen a 1\u20133rd-lvl spell 50%',
    'Fire Charm':'those gazing into the flames are charmed',
    'Rary\u2019s Mnemonic Enhancer':'hold a few extra spells',
    'Vacancy':'an area looks long-abandoned',
    'Airy Water':'water becomes breathable',
    'Avoidance':'an item repels all who near it',
    'Distance Distortion':'double or halve a path\u2019s length',
    'Leomund\u2019s Secret Chest':'stash a chest on the Ethereal',
    'Shadow Door':'illusory door; you slip away unseen',
    'Glassee':'see & reach through a wall',
    'Lower Water':'drop a body of water\u2019s level',
    'Transmute Water to Dust':'dry water & liquid to powder',
    'Spirit-Wrack':'bind & torment an outsider',
    'Charm Plants':'befriend plant creatures',
    'Duo-Dimension':'go paper-thin to hide or pass',
    'Sequester':'hide a subject from sight & scrying',
    'Demand':'compelling message, as a suggestion',
    'Glassteel':'glass gains the strength of steel',
    'Sink':'plunge a target down into the ground',
    'Crystalbrittle':'turn metal to fragile crystal',
    'Bind':'animate rope to entangle & bind',
    'Control Temperature, 10\u2019 Radius':'raise/lower local temperature',
    'Repel Insects':'insects held 10 ft away',
    'Anti-Plant Shell':'ward against plant creatures',
    'Anti-Animal Shell':'ward against natural beasts',
    'Magic Font':'scry through a holy-water basin',
    'Rainbow':'a bow of light, or a light-bridge',
    'Liveoak':'an oak wakes as your guardian',
    // — coverage fill (exact DB names) —
    'Audible Glamer':'phantom sounds from a point',
    'Mending':'repair a small break or tear',
    'Message':'whisper to 1/lvl at range',
    'Nystul\u2019s Magical Aura':'fake or mask an item\u2019s aura',
    'Phantasmal Force':'a silent visual illusion',
    'Ventriloquism':'throw your voice',
    'Blindness':'strike one target blind (save neg.)',
    'Darkness, 15\u2019 Radius':'blot out light, 15-ft globe',
    'Forget':'wipe the last few minutes\u2019 memory',
    'Improved Phantasmal Force':'illusion with sound & motion',
    'Know Alignment':'read a creature\u2019s alignment',
    'Locate Object':'sense a known object\u2019s direction',
    'Protection from Cantrips':'ward vs cantrips, 1 day/lvl',
    'Shatter':'shatter brittle objects in 60 ft',
    'Spectral Hand':'floating hand delivers touch spells',
    'Tasha\u2019s Uncontrollable Hideous Laughter':'target doubles over laughing',
    'Wizard Lock':'arcane-seal a door or portal',
    'Feign Death':'appear dead, resist harm',
    'Gust of Wind':'blast of wind bowls foes/flames',
    'Infravision':'see heat 60 ft, 2 hr/lvl',
    'Invisibility, 10\u2019 Radius':'hide a group until they attack',
    'Secret Page':'disguise a page\u2019s true text',
    'Wraithform':'become insubstantial & sneak',
    'Contagion':'inflict a wasting disease',
    'Fumble':'target stumbles, drops, falls (save)',
    'Leomund\u2019s Secure Shelter':'conjure a sturdy lodge',
    'Magic Mirror':'scry through a mirror',
    'Monster Summoning II':'summon 1d6 2nd-tier monsters',
    'Otiluke\u2019s Resilient Sphere':'seal target in a force globe',
    'Shadow Monsters':'quasi-real illusory monsters',
    'Bigby\u2019s Interposing Hand':'force hand blocks one foe',
    'Contact Other Plane':'ask a distant power questions',
    'Demi-Shadow Monsters':'sturdier shadow monsters',
    'Dismissal':'banish an outsider home',
    'Extension II':'lengthen a 1\u20134th-lvl spell 50%',
    'Leomund\u2019s Lamentable Belaborment':'words trap a foe in argument',
    'Monster Summoning III':'summon 1d4 3rd-tier monsters',
    'Shadow Magic':'quasi-real damaging illusion',
    'Transmute Rock to Mud':'turn rock to deep mud (or back)',
    'Anti-Magic Shell':'10-ft zone blocks all magic',
    'Demi-Shadow Magic':'stronger quasi-real spell mimicry',
    'Enchant an Item':'prime an item for enchantment',
    'Extension III':'greatly extend a spell\u2019s duration',
    'Guards and Wards':'ward a whole stronghold',
    'Mass Suggestion':'suggestion to 1/lvl at once',
    'Monster Summoning IV':'summon 1d4 4th-tier monsters',
    'Mordenkainen\u2019s Lucubration':'recall a just-cast spell',
    'Permanent Illusion':'a lasting, interactive illusion',
    'Project Image':'cast through a lifelike double',
    'Repulsion':'push creatures away from you',
    'Shades':'nearly-real shadow conjurations',
    'Bigby\u2019s Grasping Hand':'force hand grabs & holds',
    'Monster Summoning V':'summon 1d2 5th-tier monsters',
    'Statue':'turn to living stone at will',
    'Vanish':'teleport or ether an object',
    'Antipathy-Sympathy':'repel or lure a set creature type',
    'Binding':'imprison an outsider by pact',
    'Clone':'grow a duplicate of a person',
    'Monster Summoning VI':'summon 1d2 6th-tier monsters',
    'Otiluke\u2019s Telekinetic Sphere':'force globe you can move by mind',
    'Serten\u2019s Spell Immunity':'ward allies vs many spells',
    'Astral Spell':'project onto the Astral Plane',
    'Monster Summoning VII':'summon 1 mighty monster',
    'Animal Friendship':'befriend a wild animal over time',
    'Combine':'priests pool power for a leader',
    'Detect Poison':'sense poison in food/object',
    'Detect Snares & Pits':'reveal natural traps & hazards',
    'Invisibility to Undead':'undead can\u2019t see you (save)',
    'Detect Charm':'spot charmed or controlled minds',
    'Trip':'a line trips those who cross',
    'Withdraw':'accelerate your own time to rest/heal',
    'Flame Walk':'walk unharmed through fire',
    'Remove Paralysis':'free 1d4 from paralysis/hold',
    'Snare':'set a magical trap-noose',
    'Starshine':'soft starlight over a broad area',
    'Abjure':'send an outsider back home',
    'Animal Summoning I':'call 8 HD of nearby animals',
    'Cloak of Bravery':'party gains a big bonus vs fear',
    'Divination':'omen about an area or task',
    'Giant Insect':'grow insects to giant size',
    'Hallucinatory Forest':'illusory forest cloaks the land',
    'Hold Plant':'freeze plant creatures 1 rd/lvl',
    'Plant Door':'pass through plants unhindered',
    'Protection From Lightning':'absorb a pool of electricity',
    'Reflecting Pool':'scry via a still pool',
    'Animal Summoning II':'call 16 HD of animals',
    'Control Winds':'raise or still the winds',
    'Pass Plant':'step from tree to distant tree',
    'Aerial Servant':'invisible force fetches a target',
    'Animal Summoning III':'call 24 HD of animals',
    'Conjure Fire Elemental':'summon a 16-HD fire elemental',
    'Stone Tell':'question the surrounding stone',
    'Turn Wood':'drive wooden objects/foes back',
    'Animate Rock':'bring a slab of stone to life',
    'Transmute Metal to Wood':'turn a metal item to wood'
  };
})();
